altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1b2ce4f3-f492-40e6-aa1b-e160f64b74a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-11T01:03:10-07:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4f9a9096-eacd-4c85-b3fd-840580401aa4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-11T01:03:10-07:00'
            elementCondition: null
            fieldUid: 1230e3f3-1ac1-4b89-9150-35cbf1f39ff2 # Image Hero Optimized
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 089db9e6-991b-489c-bd69-1be0bb0fcc08
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 856e6a90-3d48-4dcf-bfa4-f678cc40c74d
        userCondition: null
fs: heroImages
handle: imageoptimizeHero
name: 'ImageOptimize - Hero'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: heroImages
transformSubpath: ''
