defaultPlacement: end
enableVersioning: true
entryTypes:
  - 867399f9-5cee-4f95-836b-a04cc7bc2639 # Header
handle: header
maxAuthors: 1
name: Header
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b770f7e5-3411-4c52-91e3-c5929d334207: # CraftDev
    enabledByDefault: true
    hasUrls: true
    template: _routers/router--page.twig
    uriFormat: header
type: single
