defaultPlacement: end
enableVersioning: true
entryTypes:
  - a2c173c5-4b31-4338-86ee-a0cb4aafc12b # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  b770f7e5-3411-4c52-91e3-c5929d334207: # CraftDev
    enabledByDefault: true
    hasUrls: true
    template: _routers/router--page.twig
    uriFormat: __home__
type: single
