columnSuffix: null
handle: footer
instructions: null
name: Footer
searchable: false
settings:
  createButtonLabel: 'Neuer Eintrag'
  entryTypes:
    - 1ecc4fa4-7e2d-4364-b61c-3a77a8f22390 # Footer Content
  includeTableView: false
  maxEntries: 4
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
