color: null
fieldLayouts:
  422d1564-95a5-47b0-b32c-bad04441e2b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-10T20:42:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 80a47da2-9e8e-4ab3-ba2b-c51afef6cd04
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T20:43:28+00:00'
            elementCondition: null
            fieldUid: 6a8579a0-7f72-41c9-9a9b-4d6d4f5ad746 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aee1ccf-d465-408d-95dd-eacfe6a5802f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e4d0ede-7f67-4397-b176-db196c16463a
        userCondition: null
handle: contact
hasTitleField: true
icon: id-card
name: Kontakt
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
