color: lime
fieldLayouts:
  1cc7d9a4-4dbd-442f-a66c-861094d94fb4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 41b517ef-ebca-4758-8b23-b20424780dfe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fff166a9-5cfa-4eb2-aa7c-52a2f34b8a47 # CTA Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a6fe6a4-e0b2-4f66-92f6-218130bcc919
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fab38811-fef1-4fc7-a7d4-7aeb3437eb35 # CTA Url
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bd794bb-0828-4e68-96f3-e56834c9d347
            userCondition: null
            warning: null
            width: 100
        name: CTA
        uid: 36a297b5-7921-4a69-bd07-80ddb6c4c660
        userCondition: null
handle: cta
hasTitleField: true
icon: play
name: CTA
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
