color: pink
fieldLayouts:
  904d3684-d920-433b-a7b5-968fa4ccbd65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1115b891-3a7a-44e6-8fd0-6df6898aaa80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce11b004-8f79-48e1-b31b-dbcea3a241bb # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10fb8a52-26e0-462a-9414-3cb720d77fc2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72555363-9815-48cd-bcce-d855765e7d66 # Plain Text
            handle: featureDescription
            includeInCards: false
            instructions: null
            label: 'Feature Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 952056cb-f2d1-4493-8fdd-517a41823f39
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fdb24d42-eb90-405d-959d-b64c116b4933
        userCondition: null
handle: feature
hasTitleField: false
icon: tag
name: Feature
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{FeatureDescription}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
