color: null
fieldLayouts:
  3924ceb9-9453-47ca-a7c1-573e9103730a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-10T21:58:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 958be9ab-f991-4865-b7a8-d41189dec41d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T22:00:31+00:00'
            elementCondition: null
            fieldUid: bdf32217-a781-41f4-8a9d-ba623b04e90a # Image Content
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b62da29-1b6c-4442-a757-13b824ea94c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T22:00:09+00:00'
            elementCondition: null
            fieldUid: 9dc35b77-87de-4411-91b1-05d093c994b9 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c10aa4d3-e96e-4910-9605-dc0a796be3a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba23b168-1218-49e1-8c7e-4419e33d74b5
        userCondition: null
handle: gallery
hasTitleField: true
icon: images
name: Galerie
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
