color: emerald
fieldLayouts:
  85327d99-f063-42be-b71a-f7a40544274a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 890df5a4-a742-4c34-bdc5-739922a6297e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bdf32217-a781-41f4-8a9d-ba623b04e90a # Image Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30ee2914-291d-4ce1-82c1-47fb14722261
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9dc35b77-87de-4411-91b1-05d093c994b9 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd7567e2-e9e7-475d-b0cc-4c0c8faafd3f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 287f6c8e-3c73-4ee3-9936-cbdaa3ba25fc # Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c7a6d79-1809-4394-b149-2deffeb7e823
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e2653fb-3d37-4e07-bef9-cc8e2217644a
        userCondition: null
handle: images
hasTitleField: true
icon: images
name: Images
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
