color: null
fieldLayouts:
  0bea6fb0-b5c1-47ae-b177-05b6a0d01667:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-10T21:19:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d04557bf-3e97-4d01-a4c9-5a5d071f42d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T21:20:22+00:00'
            elementCondition: null
            fieldUid: 6a8579a0-7f72-41c9-9a9b-4d6d4f5ad746 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d371f347-4a92-418c-8e42-e0bf5354378e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85e80205-1212-4404-b703-1b2e353eba5a
        userCondition: null
handle: pages
hasTitleField: true
icon: page
name: Seiten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
